publisher:
  name: Something
  address: ''
  website: https://buildsomething.fun
  email: m@buildsomething.fun
  media:
    - purpose: icon
      uri: ./media/logo_dark.png
app:
  name: Something
  address: ''
  android_package: dapp.buildsomething
  urls:
    license_url: https://buildsomething.fun/terms
    copyright_url: https://buildsomething.fun/terms
    privacy_policy_url: https://buildsomething.fun/privacy
    website: https://buildsomething.fun
  media:
    - purpose: icon
      uri: ./media/logo_dark.png
release:
  address: ''
  media:
    - purpose: icon
      uri: ./media/logo_dark.png
    - purpose: screenshot
      uri: ./media/screenshot_1.png
    - purpose: screenshot
      uri: ./media/screenshot_2.png
    - purpose: screenshot
      uri: ./media/screenshot_3.png
    - purpose: screenshot
      uri: ./media/screenshot_4.png
  files:
    - purpose: install
      uri: ./files/app-release.apk
  catalog:
    en-US:
      name: Something
      short_description: Vibecode dApps!
      long_description:
      new_in_version:
solana_mobile_dapp_publisher_portal:
  testing_instructions:

